---
title: "snpRelate cuttree on B. distachyon"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(SNPRelate)
```

## Load data

Converts the vcf to SNPRelate's special binary format. `geno` is now the handle we use for the data.

```{r loaddata}
#snpgdsVCF2GDS(Sys.glob("*.vcf"), "all-bd1-1.gds")
geno = snpgdsOpen("all-bd1-1.gds")
```

## Samples

```{r samples}
missing.rate = snpgdsSampMissRate(geno)
hist(missing.rate)
samples = snpgdsSummary(geno)$sample.id
samples.pass = samples[missing.rate <= 0.6]
```
## Show IBS matrix

```{r ibs}
ibs = snpgdsIBS(geno, maf=0.02, missing.rate=0.9, sample.id=samples.pass)
image(ibs$ibs)
```

## Cut tree and save groups

```{r cuttree}
hc = snpgdsHCluster(ibs)
tree = snpgdsCutTree(hc)
snpgdsDrawTree(tree)

pdf("cuttree.pdf", width=60, height=16)
snpgdsDrawTree(tree, leaflab = "perpendicular", cex=0.101)
dev.off()

groups.df = data.frame(sample=tree$sample.id, group=tree$samp.group, hclust.order=tree$samp.order)
write.csv(groups.df, "sample_groups.csv", row.names=F)
```

## $F_{ST}$ windows

```{r fst}

sample = gsub('-', '.', gsub("^([^:]+):?.*", "\\1", samples.pass))
sample[1] = "BD1.1" # Name reference genome correctly
meta = read.delim("~/Desktop/R_files/Brachy_META_NO_NAs.txt")
m = match(sample, meta$ID)
meta = meta[m[!is.na(m)],]
samples.pass = samples.pass[!is.na(m)]
sample=sample[!is.na(m)]
head(meta)

# jared's complete cases example
#obj.match <- match(rownames(obj.1), rownames(obj.2))
#obj.bind <- cbind(obj.match, obj.1)
#obj.crop <- obj.bind[complete.cases(obj.bind[,1]), ]
#obj.done <- obj.crop[,2:ncol(obj.crop)]



fst.windows = snpgdsSlidingWindow(gdsobj=geno, sample.id=samples.pass, winsize=1e5, shift=1e5, unit="basepair", FUN='snpgdsFst', 
                                  population=as.factor(as.character(meta$Continent)), method="W&C84", as.is="numeric")
fst.win.df = NULL
for (chr in 1:5) {
  v = fst.windows[[paste0("chr", chr, ".val")]]
  p = fst.windows[[paste0("chr", chr, ".pos")]]
  df = data.frame(fst=v, pos=p, chrom=rep(paste0("chr", chr), times=length(v)))
  fst.win.df = rbind(fst.win.df, df)
}

p = ggplot(fst.win.df, aes(pos, fst)) +
  geom_point() +
  facet_wrap(~chrom, scales="free_x", ncol = 1) +
  theme_bw()

print(p)
```
